### ISSUE TITLE
PUT文件上传漏洞，上传webshell文件上传了3分钟没回显

### ISSUE THREAD

**Issue by Superhero-zero** [errors11/TomcatVuln#4]
![image](https://github.com/errors11/TomcatVuln/assets/66772820/08d90f19-2df1-4de2-8e72-1e6d95c8a277)

**Comment by errors11** [comment]
在cmd中运行看看有没有什么错误信息，应该是报错了

**Comment by Superhero-zero** [comment]
![image](https://github.com/errors11/TomcatVuln/assets/66772820/fbac3258-7bd9-42ed-937e-8a930c42c5c0)

**Comment by errors11** [comment]
可以15897740915



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月18日(周四) 下午4:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [errors11/TomcatVuln] PUT文件上传漏洞，上传webshell文件上传了3分钟没回显 (Issue #4)




 
方便加你个微信吗，我手上有vps靶场，可以帮你调试这个工具
